<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateOurServiceItemsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('our_service_items', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('our_service_id');
            $table->string('name_th')->nullable();
            $table->string('name_en')->nullable();
            $table->text('desciption_th')->nullable();
            $table->text('desciption_en')->nullable();
            $table->text('picture');
            $table->enum('status',['active','inactive'])->default('active');
            $table->timestamps();
        });

        DB::table('our_service_items')->insert([
            // Armrest Frame Ass'y
            ['our_service_id'=>1,'picture'=>'215A9277.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9278.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9279.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9280.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9281.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9282.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9283.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9303.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9304.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9305.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9306.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9399.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9400.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9401.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9402.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9403.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9404.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9405.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9406.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9407.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9408.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9409.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9410.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9411.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9412.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9413.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9414.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'215A9415.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7973.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7974.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7975.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7976.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7977.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7978.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7979.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7980.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7981.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7982.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7983.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7984.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7985.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7986.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7987.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7988.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>1,'picture'=>'DSC_7989.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            // Bracket & Component
            ['our_service_id'=>2,'picture'=>'215A9185.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9186.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9187.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9188.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9189.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9190.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9191.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9192.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9193.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9194.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9195.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9196.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9197.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9198.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9201.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9202.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9203.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9204.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9205.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9206.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9207.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9208.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9209.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9210.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9211.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9212.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9213.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9223.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9224.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9225.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9226.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9227.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9228.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9229.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9230.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9231.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9232.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9233.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9234.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9235.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9236.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9237.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9238.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9239.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9240.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9241.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9242.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9243.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9244.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9245.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9246.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9247.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9248.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9249.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9250.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9284.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9285.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9286.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9287.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9288.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9310.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9311.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9312.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9313.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>2,'picture'=>'215A9314.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            // Cushion Frame Ass'y
            ['our_service_id'=>3,'picture'=>'215A9389.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'215A9390.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'215A9391.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'215A9416.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'215A9417.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'215A9418.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'215A9419.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'215A9430.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'215A9431.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_7990.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_7991.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_7992.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_7993.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_7994.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_7995.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_7996.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8004.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8005.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8006.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8007.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8008.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8009.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8010.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8011.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8012.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8013.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8014.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8015.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8016.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8017.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8018.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8019.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8020.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8021.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>3,'picture'=>'DSC_8022.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            // Insert Seat Cover
            ['our_service_id'=>4,'picture'=>'215A9262.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>4,'picture'=>'215A9263.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>4,'picture'=>'215A9264.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>4,'picture'=>'215A9265.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>4,'picture'=>'215A9266.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>4,'picture'=>'215A9267.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>4,'picture'=>'215A9268.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>4,'picture'=>'215A9357.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>4,'picture'=>'215A9358.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>4,'picture'=>'215A9359.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>4,'picture'=>'215A9360.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            // Lock Unit Ass'y
            ['our_service_id'=>5,'picture'=>'215A9257.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9258.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9259.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9260.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9261.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9297.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9298.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9299.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9300.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9301.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9302.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9326.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9327.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9328.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9329.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9330.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9331.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9332.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9333.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9334.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9335.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9336.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9337.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9338.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9339.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9340.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9341.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9342.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9343.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9344.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9345.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9346.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9347.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9348.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9420.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9421.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9422.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9423.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9424.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9425.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9426.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9427.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9428.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'215A9429.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'DSC_7997.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'DSC_7998.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'DSC_7999.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'DSC_8000.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'DSC_8001.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'DSC_8002.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>5,'picture'=>'DSC_8003.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            // Pipe Bending
            ['our_service_id'=>6,'picture'=>'215A9269.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9270.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9271.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9272.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9273.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9274.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9275.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9276.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9289.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9290.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9291.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9307.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9308.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9309.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9315.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9316.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9317.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9318.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9319.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9320.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9321.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9322.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9323.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9324.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9325.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9353.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9354.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9355.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9356.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'215A9361.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7906.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7907.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7908.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7909.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7910.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7911.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7912.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7913.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7914.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7915.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7916.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7917.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7918.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7919.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7920.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7921.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7922.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7923.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7924.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>6,'picture'=>'DSC_7925.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            // Pipe Sub Ass'y
            ['our_service_id'=>7,'picture'=>'215A9349.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9350.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9351.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9352.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9382.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9383.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9384.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9385.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9386.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9387.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9388.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9392.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9393.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9394.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9395.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9396.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9397.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'215A9398.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7953.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7954.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7955.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7956.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7957.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7958.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7959.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7960.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7961.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7962.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7963.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7964.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7965.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7966.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7967.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7968.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7969.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7970.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7971.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>7,'picture'=>'DSC_7972.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            // Seat Frame Assembly
            ['our_service_id'=>8,'picture'=>'215A9182.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9184.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9362.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9363.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9364.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9365.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9366.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9367.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9368.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9369.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9370.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9371.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9372.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9373.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9374.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9375.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9376.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9377.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9378.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9379.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9380.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'215A9381.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_5780.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_5781.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_5782.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_5783.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_5784.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_5785.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_5786.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_5787.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7926.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7927.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7928.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7929.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7930.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7931.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7932.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7933.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7934.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7935.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7936.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7937.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7938.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7939.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7940.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7941.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7942.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7943.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7944.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7945.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7946.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7947.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7948.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7949.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7950.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7951.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>8,'picture'=>'DSC_7952.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            // Wire Bending
            ['our_service_id'=>9,'picture'=>'215A9215.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9216.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9217.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9218.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9219.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9220.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9221.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9222.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9251.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9252.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9253.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9254.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9255.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9256.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9292.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9293.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9294.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9295.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
            ['our_service_id'=>9,'picture'=>'215A9296.jpg','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('our_service_items');
    }
}
